version: '2'

services:
  front:
    build: front
    env_file: .env
    volumes:
      - /work/assets
      - ./front:/work
    command: npm start

  back:
    build: back
    depends_on:
      - db
    env_file: .env
    volumes:
      - /work/static
      - ${MEDIA_ROOT}:/work/media
      - ./back:/work
    networks:
      - front
      - back
    volumes_from:
      - front
    command: bash -c "python manage.py livereload --host 0.0.0.0 /work/assets/ & python manage.py runserver 0.0.0.0:80"
    ports:
      - "${PORT}:80"
      - "${LIVERELOAD_PORT}:${LIVERELOAD_PORT}"

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - back

networks:
  front:
  back:
