version: '2'

services:
  proxy:
    image: nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./proxy/nginx_conf:/etc/nginx/conf.d
      - ${MEDIA_ROOT}:/work/media
    depends_on:
      - app-back
    networks:
      - front
    volumes_from:
      - app-front
      - app-back
    command: bash -c "groupadd -g ${MEDIA_GROUP_GID} ${MEDIA_GROUP_NAME}; usermod -G ${MEDIA_GROUP_NAME} -a nginx; nginx -g 'daemon off;'"

  app-front:
    build: app-front
    env_file: .env
    volumes:
      - /work/assets

  app-back:
    build: app-back
    depends_on:
      - db
    env_file: .env
    volumes:
      - /work/static
      - ${MEDIA_ROOT}:/work/media
      - ./app-back:/work
    networks:
      - front
      - back
    volumes_from:
      - app-front

  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - back

networks:
  front:
  back:
