version: '2'

services:
  proxy:
    image: nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./proxy/nginx_conf:/etc/nginx/conf.d
      - ${MEDIA_ROOT}:/work/media
    depends_on:
      - back
    networks:
      - front
    volumes_from:
      - front
      - back
    command: bash -c "groupadd -g ${MEDIA_GROUP_GID} ${MEDIA_GROUP_NAME}; usermod -G ${MEDIA_GROUP_NAME} -a nginx; nginx -g 'daemon off;'"

  front:
    build: front
    env_file: .env
    volumes:
      - /work/assets
    tty: true

  back:
    build: back
    depends_on:
      - db
    env_file: .env
    volumes:
      - /work/static
      - ${MEDIA_ROOT}:/work/media
      - ./back:/work
    networks:
      - front
      - back
    volumes_from:
      - front

  db:
    image: postgres:11
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - back

networks:
  front:
  back:
