FROM python:3.8
ENV PYTHONUNBUFFERED 1

WORKDIR /work

RUN pip install pipenv uwsgi
COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system --dev

COPY . ./
RUN python manage.py migrate; python manage.py collectstatic --noinput
CMD python manage.py runserver 0.0.0.0:80
EXPOSE 80
