# Generated by Django 2.1 on 2018-11-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='viewer.Author')),
            ],
        ),
    ]
