# Generated by Django 2.1 on 2020-05-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20181124_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='manga', max_length=20),
            preserve_default=False,
        ),
    ]
