# Generated by Django 2.1 on 2020-05-03 08:04

from django.db import migrations, models
from pathlib import Path


def forwards_func(apps, schema_editor):
    Book = apps.get_model('viewer', 'Book')
    for book in Book.objects.all():
        directory = Path(book.type) / Path('_'.join([author.name for author in book.authors.all()])) / Path(book.title)
        if book.volume:
            directory /= Path(str(book.volume))
        book.directory = Path(str(directory).replace(' ', '_'))
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20200503_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='directory',
            field=models.CharField(max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='book',
            name='directory',
            field=models.CharField(max_length=255, null=False, unique=True),
            preserve_default=False,
        ),
    ]
