# Generated by Django 2.1 on 2020-05-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_book_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
