FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /work
WORKDIR /work
ADD requirements.txt /work/
RUN pip install -r requirements.txt
ADD . /work/

RUN pip install uwsgi
ENV STATIC_ROOT /work/static
RUN python manage.py collectstatic --noinput
CMD uwsgi --http :80 --wsgi-file app/wsgi.py
EXPOSE 80
